name: Generate IPTV Playlist

# Pemicu (Trigger): Action ini akan berjalan jika:
# 1. Ada push ke branch 'master' yang mengubah file .json di dalam folder 'mio'
# 2. Atau bisa dijalankan secara manual dari tab Actions
on:
  push:
    branches:
      - master
    paths:
      - 'mio/**.json'
  workflow_dispatch:

# Izin yang diperlukan untuk mempublikasikan ke GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Menggunakan mesin virtual Ubuntu
    steps:
      # Langkah 1: Mengambil kode dari repositori Anda
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Menyiapkan lingkungan Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Menggunakan Node.js versi 18 atau lebih tinggi

      # Langkah 3: Menjalankan skrip untuk membuat file M3U
      - name: Run script to generate M3U file
        run: node generate-m3u.js

      # Langkah 4: Mempersiapkan artifact (hasil) untuk GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Langkah 5: Mengunggah artifact dari folder 'dist'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Folder tempat playlist.m3u disimpan

      # Langkah 6: Mempublikasikan ke GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4￼Enter
